In [1]:
import numpy as np 

In [2]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [3]:
type(a)

numpy.ndarray

In [4]:
type(a[0])

numpy.float64

In [6]:
a = np.zeros(3, dtype=int)
type(a[0])

numpy.int32

In [7]:
z = np.zeros(10)

In [8]:
z.shape

(10,)

In [11]:
z.shape = (10, 1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [13]:
z = np.zeros(4)
z.shape = (2, 2)
z

array([[0., 0.],
       [0., 0.]])

In [15]:
z = np.zeros((2,2))
z

array([[0., 0.],
       [0., 0.]])

In [19]:
z = np.empty(3)
z += 1
z

array([1., 1., 1.])

In [20]:
z = np.linspace(2, 4, 5)
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [21]:
z = np.identity(2)
z

array([[1., 0.],
       [0., 1.]])

In [23]:
z = np.array([10, 20])
z

array([10, 20])

In [24]:
type(z)

numpy.ndarray

In [26]:
z = np.array([10, 20], dtype=float)
z

array([10., 20.])

In [28]:
z = np.array([[10, 20], [10, 30]])
z

array([[10, 20],
       [10, 30]])

In [29]:
na = np.linspace(10, 20, 2)
na is np.asarray(na)

True

In [30]:
na is np.array(na)

False

In [31]:
z = np.linspace(1, 2, 5)
z

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [32]:
z[0]

1.0

In [33]:
z[0:2]

array([1.  , 1.25])

In [34]:
z[-1]

2.0

In [36]:
z = np.array([[1, 2], [3, 4]])
z

array([[1, 2],
       [3, 4]])

In [37]:
z[0, 0]

1

In [38]:
z[0, 1]

2

In [39]:
z[0, : ]

array([1, 2])

In [40]:
z = np.linspace(2, 4, 5)
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [41]:
indices = np.array((0, 2, 3))
indices

array([0, 2, 3])

In [42]:
z[indices]

array([2. , 3. , 3.5])

In [43]:
z = np.linspace(2, 4, 5)
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [44]:
d = np.array([0, 1, 1, 0, 0], dtype=bool)
d

array([False,  True,  True, False, False])

In [45]:
z[d]

array([2.5, 3. ])

In [46]:
z = np.empty(3)
z

array([2. , 3. , 3.5])

In [47]:
z[:] = 42
z

array([42., 42., 42.])

In [49]:
a = np.array((4, 3, 2, 1))
a

array([4, 3, 2, 1])

In [51]:
a.sort()
a

array([1, 2, 3, 4])

In [52]:
a.sum()

10

In [53]:
a.mean()

2.5

In [54]:
a.max()

4

In [55]:
a.argmax()

3

In [56]:
a.cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [57]:
a.var()

1.25

In [59]:
a.std()

1.118033988749895

In [61]:
a.shape = (2, 2)
a.T

array([[1, 3],
       [2, 4]])

In [62]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [63]:
z = np.linspace(2, 4, 5)
z
z.searchsorted(2.2)

1

In [64]:
a = np.array((4, 3, 2, 1))

In [65]:
np.sum(a)

10

In [66]:
np.mean(a)

2.5

In [67]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
a + b

array([ 6,  8, 10, 12])

In [68]:
a * b

array([ 5, 12, 21, 32])

In [69]:
a + 10

array([11, 12, 13, 14])

In [70]:
a * 10

array([10, 20, 30, 40])

In [72]:
A = np.ones((2, 2))
B = np.ones((2, 2))
A + B

array([[2., 2.],
       [2., 2.]])

In [73]:
A + 10

array([[11., 11.],
       [11., 11.]])

In [74]:
A * B

array([[1., 1.],
       [1., 1.]])

In [75]:
A = np.ones((2, 2))
B = np.ones((2, 2))
A @ B

array([[2., 2.],
       [2., 2.]])

In [77]:
A = np.array((1, 2))
B = np.array((10, 20))
A @ B

50

In [78]:
A = np.array(((1, 2), (3, 4)))
A

array([[1, 2],
       [3, 4]])

In [86]:
A @ (0, 1)

array([2, 4])

In [87]:
a = np.array([42, 44])
a

array([42, 44])

In [88]:
a[-1] = 0
a

array([42,  0])

In [89]:
a = np.random.randn(3)
a

array([-0.67306831, -0.26474137, -1.3895767 ])

In [90]:
b = a
b[0] = 0.0
a

array([ 0.        , -0.26474137, -1.3895767 ])

In [91]:
a = np.random.randn(3)
a

array([ 0.01438669, -0.53171096, -1.32139193])

In [92]:
b = np.copy(a)
b

array([ 0.01438669, -0.53171096, -1.32139193])

In [93]:
b[:] = 1
b

array([1., 1., 1.])

In [94]:
a

array([ 0.01438669, -0.53171096, -1.32139193])

In [95]:
z = np.array([1, 2, 3])
np.sin(z)

array([0.84147098, 0.90929743, 0.14112001])

In [96]:
n = len(z)
y = np.empty(n)
for i in range(n):
    y[i] = np.sin(z[i])

In [97]:
z

array([1, 2, 3])

In [98]:
(1 / np.sqrt(2 * np.pi)) * np.exp(-0.5 * z ** 2)

array([0.24197072, 0.05399097, 0.00443185])

In [99]:
def f(x):
    return 1 if x > 0 else 0


In [104]:
x = np.random.randn(4)
x

array([ 1.59878346,  0.53431096,  1.34130604, -0.09624498])

In [105]:
np.where(x > 0, 1, 0)

array([1, 1, 1, 0])

In [106]:
def f(x): return 1 if x > 0 else 0
f = np.vectorize(f)
f(x)

array([1, 1, 1, 0])

In [107]:
z = np.array([2, 3])
y = np.array([2, 3])
z == y

array([ True,  True])

In [108]:
y[0] = 5
z == y

array([False,  True])

In [109]:
z != y

array([ True, False])

In [110]:
z = np.linspace(0, 10, 5)
z
z > 3

array([False, False,  True,  True,  True])

In [111]:
b = z > 3
b

array([False, False,  True,  True,  True])

In [112]:
z[b]

array([ 5. ,  7.5, 10. ])

In [113]:
z[z > 3]

array([ 5. ,  7.5, 10. ])

In [114]:
z = np.random.randn(10000)
y = np.random.binomial(10, 0.5, size = 1000)
y.mean()

5.048

In [115]:
A = np.array([[1, 2], [3, 4]])
np.linalg.det(A)

-2.0000000000000004

In [116]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])